#ifndef GAME_CONFIG_GAME_CONFIG_H
#define GAME_CONFIG_GAME_CONFIG_H

#include "game2/config/reference/reference_style.h"

#define GAME_SCREEN_WIDTH GAME_REF_SCREEN_WIDTH
#define GAME_SCREEN_HEIGHT GAME_REF_SCREEN_HEIGHT

#define GAME_STATUS_BAR_HEIGHT GAME_REF_STATUS_BAR_HEIGHT
#define GAME_ACTION_BAR_HEIGHT GAME_REF_ACTION_BAR_HEIGHT

#define GAME_PLAY_AREA_X GAME_REF_PLAY_AREA_X
#define GAME_PLAY_AREA_Y GAME_REF_PLAY_AREA_Y
#define GAME_PLAY_AREA_WIDTH GAME_REF_PLAY_AREA_WIDTH
#define GAME_PLAY_AREA_HEIGHT GAME_REF_PLAY_AREA_HEIGHT

#define GAME_TILE_SIZE GAME_REF_TILE_SIZE
#define GAME_MAP_COLS GAME_REF_MAP_COLS
#define GAME_MAP_ROWS GAME_REF_MAP_ROWS

#define GAME_CHARACTER_RENDER_SIZE GAME_REF_CHARACTER_RENDER_SIZE

#define GAME_FARM_ROWS 3
#define GAME_FARM_COLS 3

#endif
