#ifndef GAME_CONFIG_REFERENCE_STYLE_H
#define GAME_CONFIG_REFERENCE_STYLE_H

// Frozen baseline from ÂèÇËÄ?config.h and ÂèÇËÄ?character.cpp.

#define GAME_REF_SCREEN_WIDTH 240
#define GAME_REF_SCREEN_HEIGHT 240

#define GAME_REF_STATUS_BAR_HEIGHT 24
#define GAME_REF_ACTION_BAR_HEIGHT 40

#define GAME_REF_PLAY_AREA_X 8
#define GAME_REF_PLAY_AREA_Y 24
#define GAME_REF_PLAY_AREA_WIDTH 224
#define GAME_REF_PLAY_AREA_HEIGHT 176

#define GAME_REF_TILE_SIZE 16
#define GAME_REF_MAP_COLS 14
#define GAME_REF_MAP_ROWS 11

#define GAME_REF_CHARACTER_BASE_SIZE 8
#define GAME_REF_CHARACTER_SCALE 2
#define GAME_REF_CHARACTER_RENDER_SIZE (GAME_REF_CHARACTER_BASE_SIZE * GAME_REF_CHARACTER_SCALE)
#define GAME_REF_CHARACTER_WALK_FRAMES 2

#define GAME_REF_CHAR_ARMOR_COLOR 0xAD55
#define GAME_REF_CHAR_SUIT_COLOR 0x5326
#define GAME_REF_CHAR_VISOR_COLOR 0x07FF

#define GAME_REF_COLOR_BLACK 0x0000
#define GAME_REF_COLOR_WHITE 0xFFFF
#define GAME_REF_COLOR_YELLOW 0xFFE0
#define GAME_REF_COLOR_CYAN 0x07FF
#define GAME_REF_COLOR_ORANGE 0xFD20
#define GAME_REF_COLOR_BG_PANEL 0x2128

#endif
