#ifndef GAME_CONFIG_REFERENCE_INPUT_PROFILE_H
#define GAME_CONFIG_REFERENCE_INPUT_PROFILE_H

#define GAME_REF_JOYSTICK_CENTER 512
#define GAME_REF_JOYSTICK_DEADZONE 150

#define GAME_REF_BUTTONS_USE_PULLUP 1
#define GAME_REF_BUTTON_ACTIVE_LOW 1

#define GAME_REF_MOVE_COOLDOWN_MS 150

#endif
